FidelityBlog/FidelityBlog/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    # path('', include('django.contrib.auth.url')),
    path('groups/', include('groups.urls', namespace="groups")), 
    # path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    # path('accounts/logout/', auth_views.logoutView.as_view(), name = 'logout', kwargs={'next_page':'/'})
    # path('accounts/login', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    # path('accounts/logout', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
]
 

FidelityBlog/blog/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

# app_name= 'blog'

urlpatterns = [
    path("", views.PostListView.as_view(), name='post_list'),
    path('accounts/login', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('accounts/logout', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('about/', views.AboutView.as_view(),name='about'),
    path('test/', views.TestView.as_view(),name='test'),
    path('thanks/', views.ThanksView.as_view(),name='thanks'),
    path("post/<int:pk>", views.PostDetailView.as_view(), name="post_detail"),
    path("createpost/", views.CreatePostView.as_view(), name="create_post"),
    path("updatepost/<int:pk>", views.PostUpdateView.as_view(), name="post_edit"), 
    path("deletepost/<int:pk>", views.PostDeleteView.as_view(), name="delete_post"),
    path("drafts/", views.DraftListView.as_view(), name="post_draft_list"),
    path("comment/<int:pk>", views.add_comment_to_post, name="add_comment_to_post"),
    path("approve_comment/<int:pk>", views.approve_comment, name="approve_comment"),
    path("delete_comment/<int:pk>", views.delete_comment, name="delete_comment"),
    path("publish_post/<int:pk>", views.publish_post, name="publish_post"),
    path("post_group/", views.PostList.as_view(), name="all"),
    path("new_group_post/", views.CreatePost.as_view(), name="create"),
    path("by/<username>", views.UserPosts.as_view(), name="for_user"),
    path("by/<username>/<int:pk>", views.PostDetail.as_view(), name="single"),
    path("delete/<int:pk>", views.DeletePost.as_view(), name="delete"),
]

FidelityBlog/blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib import auth
from django.conf import settings
# import misaka

from groups.models import Group
from django.contrib.auth import get_user_model
User = get_user_model()



# class User(auth.models.User, auth.models.PermissionsMixin):

#     def __str__(self):
#         return "@{}".format(self.username)

class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null = True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def approved_comments(self):
        return self.comments.filter(is_approved = True)


    def get_absolute_url(self):
        return reverse('post_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title


class PostGroup(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='postsgroup')
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    group = models.ForeignKey(Group, on_delete=models.CASCADE, related_name='postsgroup', null=True, blank='True' )


    def __str__(self):
        return self.message

    def get_absolute_url(self):
        return reverse('single', kwargs={'username':self.user.username, 'pk':self.pk}) 
    class Meta:
        ordering = ['-created_at']
        unique_together = ['user', 'message']

class Comment(models.Model):
    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE, related_name= 'comments')
    author = models.CharField(max_length=150)
    text = models.TextField()
    create_date = models.DateTimeField(default=timezone.now)
    is_approved = models.BooleanField(default=False)

    def approve(self):
        self.is_approved = True
        self.save()

    def get_absolute_url(self):
        return reverse('post_list')

    def __str__(self):
        return self.text

FidelityBlog/blog/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms
from blog.models import Post, Comment, PostGroup
from . import models



class UserForm(UserCreationForm):

    class meta():
        fields = ('username', 'email', 'password', 'password2',)
        model = get_user_model()

    email = forms.EmailField(required=True, label = 'Email Address')


    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['username'].label = 'Display Name'
        self.fields['email'].label = 'Email Address'
    


class PostForm(forms.ModelForm):

    class Meta():
        model = Post
        fields = ('author', 'title', 'text' )

        widgets ={
            'author': forms.Select(attrs= {'class': 'textinputclass custom-select rounded-0'}),
            'title': forms.TextInput(attrs= {'class': 'textinputclass form-control  rounded-0'}),
            'text': forms.Textarea(attrs={'class': 'editable medium-editor-textarea post-content'})
        }


class CommentForm(forms.ModelForm):

    class Meta():
        model = Comment
        fields = ('author', 'text')

        widgets={
            'author': forms.TextInput(attrs={'class': 'textinputclass form-control rounded-0'}),
            'text':forms.Textarea(attrs={'class': 'editable medium-editor-textarea comment-content'})
        }


class GroupPostForm(forms.ModelForm):
    class Meta:
        fields = ("message", "group")
        model = PostGroup

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)
        if user is not None:
            self.fields["group"].queryset = (
                models.Group.objects.filter(
                    pk__in=user.groups.values_list("group__pk")
                )
            )

FidelityBlog/blog/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.utils import timezone
from django.contrib.auth import get_user_model
from .models import Post, Comment,PostGroup
from django.urls import reverse_lazy
from .forms import PostForm, CommentForm, UserForm, GroupPostForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (TemplateView, ListView, DetailView,CreateView, UpdateView, DeleteView, ListView)
from django.http import Http404
from braces.views import SelectRelatedMixin
from django.contrib import messages
from . import forms
# from . import models 


User = get_user_model()

class SignUp(CreateView):
    form_class = UserForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

class AboutView(TemplateView):
    template_name = 'about.html'

class TestView(TemplateView):
    template_name = 'test.html'

class ThanksView(TemplateView):
    template_name = 'thanks.html'

class IndexView(TemplateView):
    template_name = 'post_list.html'

class PostListView(ListView):
    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')

    template_name = 'post_list.html'

class PostDetailView(DetailView):
    model = Post
    
class CreatePostView(LoginRequiredMixin,CreateView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_detail.html'
    form_class = PostForm
    model = Post

class PostUpdateView(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_detail.html'
    form_class = PostForm
    model = Post

class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('post_list')

class DraftListView(LoginRequiredMixin, ListView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_list.html'
    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__isnull = True).order_by('created_date')

    # template_name = 'post_draft_list.html'

@login_required
def publish_post(request, pk):
    print(f"pk: {pk}")
    post =get_object_or_404(Post,pk = pk)
    post.publish()
    return redirect('post_detail', pk= pk)


@login_required
def add_comment_to_post(request, pk):
    post = get_object_or_404(Post,pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid:
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('post_detail', pk = post.pk)
    else:
        form = CommentForm()
        return render(request, 'blog/comment_form.html', {'form':form})

@login_required
def approve_comment(request, pk):
    comment = get_object_or_404(Comment,pk=pk)
    comment.approve()
    return redirect('post_detail', pk = comment.post.pk)

@login_required
def delete_comment(request, pk):
    comment = get_object_or_404(Comment,pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    redirect('post_detail', pk=post_pk)



class PostList(SelectRelatedMixin, ListView):
    model = PostGroup
    select_related = ("user", "group")
    template_name = "blog/group_post_list.html"

class UserPosts(ListView):
    model = PostGroup
    template_name = "blog/group_user_post_list.html"

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related("postsgroup").get(
                username__iexact=self.kwargs.get("username")
            )
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post_user"] = self.post_user
        return context


class PostDetail(SelectRelatedMixin,DetailView):
    model = PostGroup
    select_related = ("user", "group")
    template_name = "blog/group_post_detail.html"

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(
            user__username__iexact=self.kwargs.get("username")
        )


class CreatePost(LoginRequiredMixin, SelectRelatedMixin, CreateView):
    fields = ('message', 'group')
    model = PostGroup
    # form_class = GroupPostForm
    template_name = "blog/group_post_form.html"


    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class DeletePost(LoginRequiredMixin, SelectRelatedMixin, DeleteView):
    model = PostGroup
    select_related = ("user", "group")
    success_url = reverse_lazy("all")
    template_name = "blog/group_post_confirm_delete.html"


    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, "Post Deleted")
        return super().delete(*args, **kwargs)

FidelityBlog/blog/templates/blog/_post.html
<div class="my-5">
        
    <h5 class="">
        <span class="username"><a href="{% url 'for_user' username=postgroup.user.username %}">@{{ postgroup.user.username }}</a></span>
        <time class="time"><a href="{% url 'single' username=postgroup.user.username pk=postgroup.pk %}">{{ postgroup.created_at }}</a></time>
        {% if postgroup.group %}
        <span class="group-name">in <a href="#" class="ml-1">{{ postgroup.group.name }}</a></span>
        {% endif %}
    </h5>



</div>


<div class=" ">
    <h3>{{ postgroup.message|safe }}</h3>
    <p><strong>{{ postgroup.user.username }}</strong></p>
        {% if user.is_authenticated and postgroup.user == user and not hide_delete %}
            <a href="{% url 'delete' pk=postgroup.pk %}" title="delete" class="btn btn-sm btn-white">
                <span class="fa fa-remove text-danger" aria-hidden="true"></span>
                <span class="text-danger icon-label">Delete</span>
            </a>
        {% endif %}
    

</div>
    

FidelityBlog/blog/templates/blog/about.html
{% extends "blog/base.html" %}

{%block body%}   
<h2>ABOUT ME</h2>
{%endblock%}

FidelityBlog/blog/templates/blog/comment_form.html
{% extends "blog/base.html" %}

{% block body %}
<h1>New Comment</h1>
<form class="post-form" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="btn btn-default save">Post comment</button>
</form>

<script>
var editor = new MediumEditor('.editable');
</script>
{% endblock %}

FidelityBlog/blog/templates/blog/group_post_base.html
{% extends "blog/base.html" %}

{% block body %}
<div class="posts-page">
    <div class="container">
        <div class="row">
            {% block prepost%}{% endblock %}
            {% block post_content %}{% endblock %}
            {% block post_post%}{% endblock %}
        </div>
    </div>
</div>
{% endblock %}

FidelityBlog/blog/templates/blog/group_post_confirm_delete.html
{% extends "blog/group_post_base.html" %}


{% block post_content %}
<h3>Are you sure you want to delete this post?</h3>

<div class="posts">
    {% include "blog/_post.html" with post=object hide_delete=True %}
</div>

<form method="POST">
    {% csrf_token %}
    <input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
    <a href="{% url 'single' username=user.username pk=object.pk %}" class="btn btn-simple btn-large btn-default">Cancel</a>
</form>

{% endblock %}

FidelityBlog/blog/templates/blog/group_post_detail.html
{% extends "blog/group_post_base.html" %}

{% block post_content %}
<div class="col-md-8">
    {% include "blog/_post.html" %}
</div>
{% endblock %}

FidelityBlog/blog/templates/blog/group_post_form.html
{% extends "blog/group_post_base.html" %}

{% load bootstrap3 %}

{% block post_content %}
<h4>Create New Post</h4>

<div class="container">
    <form method="POST" action="{% url 'create' %}" id="postForm">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Post" class="btn btn-primary btn-md">
    </form>
</div>
{% endblock %}

FidelityBlog/blog/templates/blog/group_post_list.html
{% extends "blog/group_post_base.html" %}
{% load humanize %}

{% block pre_post_content %}
<div class="col-md-4">
    {% if request.user.is_authenticated %}
    <div class="card card-with-shadow">
        <div class="content">
            <h5 class="title green-text">Your Groups</h5>
            <ul class="list-unstyled">
                {# {% get_user_groups as user_groups %}#}
                {% for member_group in get_user_groups %}
                <li class="group li-with-bullet">
                    <a href="{% url 'groups:single' slug=member_group.group.slug %}">{{ member_group.group.name }}</a>
                </li>
                {% endfor %}

            </ul>
        </div>
    </div>
    {% endif %}
    <div class="card card-with-shadow">
        <div class="content">
            <h5 class="title">All groups</h5>
            <ul class="list-unstyled">
                {# {% get_other_groups as other_groups %}#}
                {% for other_group in get_other_groups %}
                    <li class="group li-with-bullet"><a href="{% url 'groups:single' slug=other_group.slug %}">{{ other_group.name }}</a></li>
                {% endfor %}
            </ul>
            



        </div>
    </div>
</div>
{% endblock %}
{% block post_content %}
<div class="col-md-8">
    {% for post in post_list %}
  {% include "posts/_post.html" %}
    {% endfor %}
</div>
{% endblock %}

FidelityBlog/blog/templates/blog/group_user_post_list.html
{% extends "blog/group_post_base.html" %}

{% block prepost %}
<div class="col-md-3">
    <h1>@{{ post_user.username  }}</h1>
    <p class="white-text">Post History</p>
</div>
{% endblock %}

{% block post_content %}
<div class="col-md-7">
    {% for post in postgroup_list %}
        {% include "blog/_post.html" %}
    {% endfor %}
</div>
{% endblock %}

FidelityBlog/blog/templates/blog/post_confirm_delete.html
{% extends "blog/base.html" %}

{%block body%}   
<form method="POST">
{% csrf_token %}
<p>Are you sure you want to delete {{ object }}?</p>
<input type="submit" class="btn btn-danger" value="confirm">
</form>
{%endblock%}

FidelityBlog/blog/templates/blog/post_draft_list.html
{% extends "blog/base.html" %}

{% block body %}

{% for post in posts %}
<div class="post">
    <p class="date">created: {{post.create_date|date:'d-m-Y'}}</p>
    <h1><a href="{% url 'post_detail' pk=post.pk %}">{{post.title}}</a></h1>
    <p>{{post.text|truncatechars:200}}</p>
</div>
{% empty %}
        <h4 class="mt-4 alert alert-info text-center">No post</h4>
{% endfor %}
{% endblock %}

FidelityBlog/blog/templates/blog/post_form.html
{% extends "blog/base.html" %}

{% block body %}
<h1 class="font-weight-bold mt-3">New Post</h1>
<form  method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="btn btn-default btn-md  save">Save</button>
</form>

<script>
var editor = new MediumEditor('.editable');
</script>
{% endblock %}

FidelityBlog/blog/templates/blog/test.html
{% extends 'blog/base.html' %}

{% block body %}
<h1 class="mt-3">You are now logged in!</h1>
{% endblock %}

FidelityBlog/blog/templates/blog/thanks.html
{% extends 'blog/base.html' %}

{% block body %}
<h1 class="mt-3">
    Thanks for visiting, come back soon!
</h1>

{% endblock %}