FidelityBlog/FidelityBlog/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    # path('', include('django.contrib.auth.url')),
    path('groups/', include('groups.urls', namespace="groups")), 
    # path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    # path('accounts/logout/', auth_views.logoutView.as_view(), name = 'logout', kwargs={'next_page':'/'})
    # path('accounts/login', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    # path('accounts/logout', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
]
 

FidelityBlog/blog/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

# app_name= 'blog'

urlpatterns = [
    path("", views.PostListView.as_view(), name='post_list'),
    path('accounts/login', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('accounts/logout', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('about/', views.AboutView.as_view(),name='about'),
    path('test/', views.TestView.as_view(),name='test'),
    path('thanks/', views.ThanksView.as_view(),name='thanks'),
    path("post/<int:pk>", views.PostDetailView.as_view(), name="post_detail"),
    path("createpost/", views.CreatePostView.as_view(), name="create_post"),
    path("updatepost/<int:pk>", views.PostUpdateView.as_view(), name="post_edit"), 
    path("deletepost/<int:pk>", views.PostDeleteView.as_view(), name="delete_post"),
    path("drafts/", views.DraftListView.as_view(), name="post_draft_list"),
    path("comment/<int:pk>", views.add_comment_to_post, name="add_comment_to_post"),
    path("approve_comment/<int:pk>", views.approve_comment, name="approve_comment"),
    path("delete_comment/<int:pk>", views.delete_comment, name="delete_comment"),
    path("publish_post/<int:pk>", views.publish_post, name="publish_post"),
    path("post_group/", views.PostList.as_view(), name="all"),
    path("new_group_post/", views.CreatePost.as_view(), name="create"),
    path("by/<username>", views.UserPosts.as_view(), name="for_user"),
    path("by/<username>/<int:pk>", views.PostDetail.as_view(), name="single"),
    path("delete/<int:pk>", views.DeletePost.as_view(), name="delete"),
]

FidelityBlog/groups/urls.py
from django.urls import path

from . import views

app_name = 'groups'

urlpatterns = [
    path("groups", views.ListGroup.as_view(), name="all"),
    path("new", views.CreateGroup.as_view(), name="create"),
    path("posts/in/<slug:slug>/", views.SingleGroup.as_view(), name="single"),
    path("join/<slug:slug>/", views.JoinGroup.as_view(), name="join"),
    path("leave/<slug:slug>/", views.LeaveGroup.as_view(), name="leave"),
]

FidelityBlog/groups/models.py
from django import template
from django.db import models
from django.utils.text import slugify
from django.urls import reverse

# import misaka
# Create your models here
from django.contrib.auth import get_user_model
User = get_user_model()

register = template.Library()

class Group(models.Model):
    name = models.CharField(max_length=225, unique= True)
    slug = models.SlugField(allow_unicode = True, unique=True)
    description = models.TextField(blank=True, default='')
    member = models.ManyToManyField(User, through='GroupMember')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('groups:single', kwargs={'slug':self.slug})

    class Meta:
        ordering = ['name']

class GroupMember(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE, related_name='memberships')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_groups')

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ('group', 'user')

FidelityBlog/groups/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import (LoginRequiredMixin, PermissionRequiredMixin)
from django.urls import reverse
from django.views import generic
from .models import Group, GroupMember
from django.contrib import messages
from django.db import IntegrityError
from django.shortcuts import get_object_or_404
from . import models


class CreateGroup(LoginRequiredMixin, generic.CreateView):
    fields = ('name', 'description')
    # template_name = "groups/group_form.html"
    model = Group

class SingleGroup(generic.DetailView):
    model=Group

class ListGroup(generic.ListView):
    model = Group

class JoinGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("groups:single", kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group,slug=self.kwargs.get("slug"))

        try:
            GroupMember.objects.create(user=self.request.user,group=group)

        except IntegrityError:
            messages.warning(self.request,("Warning, already a member of {}".format(group.name)))

        else:
            messages.success(self.request,"You are now a member of the {} group.".format(group.name))

        return super().get(request, *args, **kwargs)


class LeaveGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("groups:single",kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):

        try:

            membership = GroupMember.objects.filter(
                user=self.request.user,
                group__slug=self.kwargs.get("slug")
            ).get()

        except GroupMember.DoesNotExist:
            messages.warning(
                self.request,
                "You can't leave this group because you aren't in it."
            )
        else:
            membership.delete()
            messages.success(
                self.request,
                "You have successfully left this group."
            )
        return super().get(request, *args, **kwargs)

FidelityBlog/groups/templates/groups/group_base.html
{% extends 'blog/base.html' %}

{% block body %}
<div class="container">
    <div class="row">
        {% block pregroup %}{% endblock %}
        {% block group_content %}{% endblock %}
        {% block postgroup %}{% endblock %}
    </div>
</div>

{% endblock %}

FidelityBlog/groups/templates/groups/group_detail.html
{% extends 'groups/group_base.html' %}

        {% block pregroup %}
        <div class="col-md-4 mt-4">

            <h1>{{group.name}}</h1>
            <h1>Member Count:{{ group.member.count }}</h1>

        <div class="content">

            {% if user in group.member.all %}
            <a href="{% url 'groups:leave' slug=group.slug %}" class="btn btn-warning"><span><i class="fa fa-remove mr-2"></i></span>leave group</a>
            
            {% else %}
            <a href="{% url 'groups:join' slug=group.slug %}" class="btn btn-green"><span><i class="fa fa-user-plus mr-2"></i></span>Join group</a>
            {% endif %}
        </div>
    </div>

        {% endblock %}
        {% block group_content %}
        <div class="col-md-8 mt-5">
            {% if  group.postsgroup.count == 0 %}
                <h2 class="font-weight-bold"> No posts in this group yet! </h2>

                {% else %}
                {% for post in group.posts.all %}
                    {% include "blog/_post.html" %}
                {% endfor %}
            {% endif %}
        </div>
        {% endblock %}
        <!-- {% block postgroup %}{% endblock %} -->
    

FidelityBlog/groups/templates/groups/group_form.html
{% extends "groups/group_base.html" %}
{% load bootstrap3 %}

{% block group_content %}
<h4>Create A New Group</h4>
<div class="container">

  <form method="POST" action="{% url 'groups:create' %}" id="groupForm">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="Create" class="btn btn-primary btn-large">
  </form>
</div>
{% endblock %}

FidelityBlog/groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}

{% block pregroup %}
<div class="col-md-4 mt-4">
    <div class="content">
        {% if user.is_authenticated %}
        <h2>
            Welcome back
            <a href="{% url 'for_user' username=user.username %}">@{{user.username }}</a>
        </h2>

    {% endif %}
            <h2>Groups</h2>

            <p>Welcome to the Groups Page! Select a Group with a shared interest!</p>
    </div>
    {% if user.is_authenticated %}
    <a href="{% url 'groups:create' %}" class="btn btn-md btn-fill btn-green"><span class="fa fa-plus mr-2"></span> Create New Group!</a>
    {% endif %}
</div>
{% endblock %}

{% block group_content %}
<div class="col-md-6 mt-4">
    <div class="list-group">
        {% for group in object_list %}
          <a class="list-group-item" href="{% url 'groups:single' slug=group.slug %}">
                 <h3 class="title list-group-item-heading blue-text">{{ group.name }}</h3>
            <div class="list-group-item-text container-fluid">
               <p class="blue-text">{{ group.description|safe }}</p> 
                <div class="row">
                    <div class="col-md-4 blue-text">
                        <span class="badge badge-primary">{{ group.member.count }}</span> members{{ group.member.count|pluralize }}
                    </div>
                    <div class="col-md-4 blue-text">
                        <span class="badge badge-primary">{{ group.postsgroup.count }}</span> post{{ group.postsgroup.count|pluralize }}
                    </div>
                </div>
            </div>
        </a>
        {% endfor %}
    </div>
</div>
{% endblock %}